export {
  graphSchemaVersion,
  type DiagnosticSeverity,
  type GraphDiagnostic,
  type GraphDiagnosticCode,
  type GraphEdge,
  type GraphEdgeKind,
  type GraphKind,
  type GraphNode,
  type GraphReceipt,
  type GraphSnapshot,
  type GraphStep,
  type GraphStepKind,
  type GraphTrack,
  type GraphTrackKind,
  type OrthogonalRoute,
  type Point,
  type Rect,
  type RouteSegment,
  type WorkflowCondition,
  type WorkflowGraphDefinition,
  type WorkflowGraphPreferences,
} from './ir.js';
export { projectWorkflow, type WorkflowTemplateSummary } from './project.js';
export { normalizeDefinition, type NormalizationResult } from './normalize.js';
