import type { CompletionSpec, CommandSpec, OptionSpec } from './spec';

/** Wrap a string in single quotes, escaping embedded single quotes. */
function quoteShell(s: string): string {
  return "'" + s.replace(/'/g, "'\\''") + "'";
}

/** `'name:description'` entry for zsh `_describe` (colons escaped in desc). */
function zshDescribeEntry(name: string, desc: string): string {
  const safeDesc = desc.replace(/:/g, '\\:');
  return quoteShell(name + ':' + safeDesc);
}

/** `_arguments` entries for one option (long and/or short, with [description]). */
function zshOptionEntries(o: OptionSpec): string[] {
  const descInner = o.description
    ? '[' + o.description.replace(/\\/g, '\\\\').replace(/([[\]])/g, '\\$1') + ']'
    : '';
  const entries: string[] = [];
  if (o.long) entries.push(quoteShell(o.long + descInner));
  if (o.short) entries.push(quoteShell(o.short + descInner));
  return entries;
}

function fnName(path: string[]): string {
  return '_afk_cmd_' + path.join('_');
}

function subArrName(path: string[]): string {
  return '_afk_sub_' + path.join('_');
}

function emitCommand(cmd: CommandSpec, path: string[], out: string[]): void {
  const curPath = [...path, cmd.name];

  if (cmd.subcommands.length > 0) {
    const entries = cmd.subcommands.map(s => zshDescribeEntry(s.name, s.description)).join(' ');
    out.push(`${subArrName(curPath)}=(${entries})`);
    out.push('');
  }

  out.push(`function ${fnName(curPath)} {`);
  const argEntries: string[] = [];
  for (const o of cmd.options) argEntries.push(...zshOptionEntries(o));

  if (cmd.subcommands.length > 0) {
    argEntries.push("'1:subcommand:->sub'", "'*:: :->subargs'");
    out.push(`  _arguments -C \\`);
    out.push(`    ${argEntries.join(' \\\n    ')}`);
    out.push(`  case $state in`);
    out.push(`    sub) _describe ${quoteShell(cmd.name + ' subcommand')} ${subArrName(curPath)} ;;`);
    out.push(`    subargs)`);
    out.push(`      if (( $+functions[${fnName(curPath)}_\${line[1]}] )); then`);
    out.push(`        ${fnName(curPath)}_\${line[1]}`);
    out.push(`      fi`);
    out.push(`      ;;`);
    out.push(`  esac`);
  } else {
    argEntries.push("': :->argval'");
    out.push(`  _arguments -C \\`);
    out.push(`    ${argEntries.join(' \\\n    ')}`);
    out.push(`  case $state in`);
    out.push(`    argval)`);
    out.push(`      local -a dyn`);
    out.push(`      dyn=("\${(@f)\$(afk __complete \${words[@]:1} 2>/dev/null)}")`);
    out.push(`      _describe 'value' dyn`);
    out.push(`      ;;`);
    out.push(`  esac`);
  }
  out.push(`}`);
  out.push('');

  for (const s of cmd.subcommands) emitCommand(s, curPath, out);
}

export function emitZsh(spec: CompletionSpec): string {
  const out: string[] = [];
  out.push('#compdef afk');
  out.push('# afk zsh completion - generated by `afk completion zsh`. Do not edit by hand.');
  out.push('# Static command/option data is inlined; argument-value positions call');
  out.push('# `afk __complete` (reserved for dynamic completion, currently empty).');
  out.push('');

  const topEntries = spec.commands.map(c => zshDescribeEntry(c.name, c.description)).join(' ');
  out.push(`_afk_top=(${topEntries})`);
  out.push('');

  for (const c of spec.commands) emitCommand(c, [], out);

  out.push(`function _afk {`);
  out.push(`  _arguments -C \\`);
  out.push(`    '(- :)--version[Show version]' \\`);
  out.push(`    '1:command:->top' \\`);
  out.push(`    '*:: :->cmd'`);
  out.push(`  case $state in`);
  out.push(`    top) _describe 'afk command' _afk_top ;;`);
  out.push(`    cmd)`);
  out.push(`      if (( $+functions[_afk_cmd_\${line[1]}] )); then`);
  out.push(`        _afk_cmd_\${line[1]}`);
  out.push(`      fi`);
  out.push(`      ;;`);
  out.push(`  esac`);
  out.push(`}`);
  out.push('');
  out.push('compdef _afk afk');
  return out.join('\n') + '\n';
}

function bashKey(path: string[]): string {
  // Bash variable names cannot contain hyphens; sanitize (values keep real names).
  return path.length ? path.join('_').replace(/-/g, '_') : 'TOP';
}

export function emitBash(spec: CompletionSpec): string {
  const out: string[] = [];
  out.push('# afk bash completion - generated by `afk completion bash`. Do not edit by hand.');
  out.push('# Static command/option data inlined; argument-value positions call');
  out.push('# `afk __complete` (reserved for dynamic completion, currently empty).');
  out.push('');

  const emitData = (cmd: CommandSpec, path: string[]) => {
    const curPath = [...path, cmd.name];
    const key = bashKey(curPath);
    if (cmd.subcommands.length > 0) {
      out.push(`_afk_sub_${key}="${cmd.subcommands.map(s => s.name).join(' ')}"`);
    }
    const opts: string[] = [];
    for (const o of cmd.options) {
      if (o.long) opts.push(o.long);
      if (o.short) opts.push(o.short);
    }
    if (opts.length > 0) {
      out.push(`_afk_opt_${key}="${opts.join(' ')}"`);
    }
    for (const s of cmd.subcommands) emitData(s, curPath);
  };

  out.push(`_afk_sub_TOP="${spec.commands.map(c => c.name).join(' ')}"`);
  out.push('_afk_opt_TOP="--version --help -h"');
  out.push('');
  for (const c of spec.commands) emitData(c, []);
  out.push('');

  out.push('_afk() {');
  out.push('  local cur="${COMP_WORDS[COMP_CWORD]}"');
  out.push('  local path=() w i key');
  out.push('  for ((i=1; i<COMP_CWORD; i++)); do');
  out.push('    w="${COMP_WORDS[i]}"');
  out.push('    [[ "$w" == -* ]] && continue');
  out.push('    path+=("$w")');
  out.push('  done');
  out.push('  if ((${#path[@]} == 0)); then key="TOP"; else key="$(IFS=_; echo "${path[*]}")"; fi');
  out.push('  key="${key//-/_}"  # sanitize hyphens to match variable names');
  out.push('  if [[ "$cur" == -* ]]; then');
  out.push('    local optvar="_afk_opt_${key}"');
  out.push('    COMPREPLY=( $(compgen -W "${!optvar:-}" -- "$cur") )');
  out.push('    return');
  out.push('  fi');
  out.push('  local subvar="_afk_sub_${key}"');
  out.push('  if [ -n "${!subvar:-}" ]; then');
  out.push('    COMPREPLY=( $(compgen -W "${!subvar}" -- "$cur") )');
  out.push('    return');
  out.push('  fi');
  out.push('  COMPREPLY=( $(afk __complete "${COMP_WORDS[@]:1}" 2>/dev/null) )');
  out.push('}');
  out.push('');
  out.push('complete -F _afk afk');
  return out.join('\n') + '\n';
}
