export const DEMO_SNAPSHOT: Snapshot = {
  workspace: {
    root: "/Users/demo/Projects/afk-release-ops",
    afkDirectoryPresent: true,
    eventCount: 7,
  },
  afk: {
    available: true,
    executable: "/opt/homebrew/bin/afk",
    summary: "afk 0.1.0 · 演示数据",
  },
  capabilities: [
    { id: "run", label: "单次工作流", command: "afk run", description: "领取并执行一个 backlog 项目", available: true },
    { id: "loop", label: "持续循环", command: "afk loop", description: "轮询、实现、QA 与完成的守护工作流", available: true },
    { id: "qa", label: "质量验证", command: "afk qa", description: "运行 AFK 质量检查与验证流程", available: true },
    { id: "board", label: "任务看板", command: "afk board", description: "读取和维护工作项状态", available: true },
    { id: "isolate", label: "隔离环境", command: "afk isolate", description: "管理 worktree 的 Compose 隔离服务", available: true },
    { id: "tmux", label: "终端会话", command: "afk tmux", description: "管理 AFK 工作流的 tmux 会话", available: true },
  ],
  workflow: {
    configPath: "/Users/demo/Projects/afk-release-ops/.afk/config.yml",
    source: "project",
    agentDefault: "codex",
    tmuxSession: "afk-release",
    targetBranch: "main",
    baseBranch: "main",
    maxRetries: 2,
    hardTimeoutMs: 7200000,
    completionTimeoutMs: 7200000,
    contextThreshold: 100000,
    goalBudget: 10000000,
    codex: { transport: "app-server", auth: "chatgpt", provider: "openai", profile: "release", endpoint: "ws://127.0.0.1:4500", authTokenEnv: "AFK_CODEX_TOKEN", startupTimeoutMs: 30000 },
    canvasNodes: [],
    templateName: undefined,
  },
  workflowTemplates: [
    { id: "issue-implementation", name: "Issue 实现", description: "实现需求、验证 AC、发布变更并进入 QA。", source: "builtin", steps: [{ id: "implement", role: "implementer", kind: "agent", dependsOn: [] }, { id: "verify-ac", role: "verifier", kind: "agent", dependsOn: ["implement"] }, { id: "publish", role: "system", kind: "system", dependsOn: ["verify-ac"] }, { id: "queue-qa", role: "system", kind: "system", dependsOn: ["publish"] }] },
    { id: "pre-merge-qa-verification", name: "合并前 QA", description: "在 QA 工作树中验证验收条件与集成测试。", source: "builtin", steps: [{ id: "verify-ac", role: "verifier", kind: "agent", dependsOn: [] }] },
    { id: "simple-loop", name: "简单循环", description: "单一 Agent 持续执行，直到任务完成。", source: "builtin", steps: [{ id: "run", role: "agent", kind: "agent", dependsOn: [] }] },
    { id: "sequential-review", name: "顺序审查", description: "实现、审查，并在失败时修复。", source: "builtin", steps: [{ id: "implement", role: "implementer", kind: "agent", dependsOn: [] }, { id: "review", role: "reviewer", kind: "agent", dependsOn: ["implement"] }, { id: "fix", role: "implementer", kind: "agent", dependsOn: ["review"] }] },
  ],
  workflowRuns: [
    { id: "build-20260822", status: "completed", startedAt: "2026-08-22T09:18:37+08:00", goal: "分析桌面端打包日志并生成 macOS 发布清单", provider: "codex", transport: "app-server", auth: "chatgpt", modelProvider: "openai", worktreePath: "/Users/demo/Projects/afk-release-ops/.worktrees/build-20260822", sessionId: "afk-release", branch: "afk/build-20260822" },
    { id: "incident-20260822", status: "blocked", startedAt: "2026-08-22T09:33:51+08:00", goal: "确认 OpenCode 配置异常的处理方案", provider: "opencode", worktreePath: "/Users/demo/Projects/afk-release-ops/.worktrees/incident-20260822", error: "等待负责人确认处理方式" },
  ],
  loop: { state: "running", pid: 48210, implement: { active: 1, ids: ["10"] }, qa: { active: null, queue: [] }, totals: { completed: 4, failed: 0 }, startedAt: 1787124200000, lastUpdateAt: 1787127821915 },
  agentRuntimes: [
    {
      id: "claude",
      label: "Claude Code",
      command: "claude",
      available: true,
      executable: "/opt/homebrew/bin/claude",
      summary: "2.1.18",
      status: "available",
      installation: { source: "pnpm", version: "2.1.18", checkedAt: "2026-08-22T09:33:51+08:00" },
    },
    {
      id: "codex",
      label: "Codex CLI",
      command: "codex",
      available: true,
      executable: "/opt/homebrew/bin/codex",
      summary: "0.47.0",
      status: "available",
      installation: { source: "Homebrew", version: "0.47.0", checkedAt: "2026-08-22T09:33:51+08:00" },
    },
    {
      id: "cursor",
      label: "Cursor Agent",
      command: "cursor-agent",
      available: false,
      executable: "",
      summary: "未在诊断 PATH 中发现 cursor-agent",
      status: "missing",
      installation: { source: "—", version: "", checkedAt: "2026-08-22T09:33:51+08:00" },
    },
    {
      id: "opencode",
      label: "OpenCode",
      command: "opencode",
      available: false,
      executable: "/usr/local/bin/opencode",
      summary: "已发现命令，但版本检测失败",
      status: "error",
      installation: { source: "本地全局路径", version: "", checkedAt: "2026-08-22T09:33:51+08:00" },
    },
  ],
  events: [
    {
      id: "demo-brief-01",
      timestamp: "2026-08-22T09:16:04+08:00",
      source: "brief-20260822",
      status: "queued",
      result: "整理发布说明与变更摘要",
      nextStep: "等待运行窗口分配 Agent",
      raw: '{"event":"queued","priority":"normal","task":"release-notes"}',
    },
    {
      id: "demo-build-01",
      timestamp: "2026-08-22T09:18:37+08:00",
      source: "build-20260822",
      status: "running",
      result: "Agent exec 正在分析桌面端打包日志",
      nextStep: "继续归纳签名与图标检查项",
      raw: '{"event":"agent_exec","agent":"claude","stage":"build-analysis"}',
    },
    {
      id: "demo-build-02",
      timestamp: "2026-08-22T09:20:15+08:00",
      source: "build-20260822",
      status: "completed",
      result: "Agent exec 已提取 4 个发布前检查项",
      nextStep: "生成 macOS 发布清单",
      raw: '{"event":"tool_result","items":4,"agent":"claude"}',
    },
    {
      id: "demo-quality-01",
      timestamp: "2026-08-22T09:24:09+08:00",
      source: "quality-20260822",
      status: "running",
      result: "QA validate 正在校验运行时间线",
      nextStep: "等待界面快照比对完成",
      raw: '{"event":"qa_validate","suite":"timeline-layout","progress":0.72}',
    },
    {
      id: "demo-quality-02",
      timestamp: "2026-08-22T09:27:42+08:00",
      source: "quality-20260822",
      status: "completed",
      result: "QA verify 已通过关键布局断点",
      nextStep: "准备合并验证结论",
      raw: '{"event":"verify_pass","suite":"responsive-layout"}',
    },
    {
      id: "demo-approval-01",
      timestamp: "2026-08-22T09:31:18+08:00",
      source: "approval-20260822",
      status: "waiting_confirmation",
      result: "HITL 确认 macOS 发布说明的最终措辞",
      nextStep: "等待负责人确认后生成发布包",
      raw: '{"event":"hitl_requested","reviewer":"release-owner"}',
    },
    {
      id: "demo-incident-01",
      timestamp: "2026-08-22T09:33:51+08:00",
      source: "incident-20260822",
      status: "waiting_confirmation",
      result: "等待确认 OpenCode 配置异常的处理方案",
      nextStep: "选择修复配置或跳过该运行时",
      raw: '{"event":"attention_required","runtime":"opencode"}',
    },
  ],
  containers: [
    {
      engine: "docker",
      name: "afk-runner",
      image: "ghcr.io/afk/runner:0.1.0",
      status: "Up 18 minutes",
    },
    {
      engine: "docker",
      name: "afk-observer",
      image: "ghcr.io/afk/observer:stable",
      status: "Up 18 minutes (healthy)",
    },
    {
      engine: "podman",
      name: "release-sandbox",
      image: "localhost/afk-sandbox:dev",
      status: "Up 7 minutes",
    },
  ],
  sessions: [
    { name: "afk-release", windows: "3", attached: true },
    { name: "afk-quality", windows: "2", attached: false },
  ],
};

export const DEMO_TMUX_PANES: Record<string, string> = {
  "afk-release": `AFK Control · 演示 tmux 会话\n\n$ afk run release-notes\n[09:18:37] claude: 正在分析桌面端打包日志\n[09:20:15] tool: 提取 4 个发布前检查项\n[09:31:18] hitl: 等待确认发布说明措辞\n\n演示环境：发送内容只会回显，不会执行本地命令。`,
  "afk-quality": `AFK Quality · 演示 tmux 会话\n\n$ afk verify timeline-layout\n[09:24:09] QA validate: 响应式断点比对中\n[09:27:42] QA verify: 关键布局断点已通过\n\n演示环境：此会话用于展示终端查看与确认发送交互。`,
};

export function presentationSnapshot(live: Snapshot): { snapshot: Snapshot; demo: boolean } {
  // Live IPC data is authoritative. Demo fixtures remain available to tests,
  // but must never appear automatically when a workspace has no events.
  return { snapshot: live, demo: false };
}
